# Generated by Django 5.0.6 on 2024-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='example', max_length=200)),
                ('email', models.EmailField(default='example@gmail.com', max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
