# Generated by Django 5.0.6 on 2024-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himwaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login2',
            name='phone_number',
            field=models.CharField(default='0700000001', max_length=10),
        ),
    ]
