# Generated by Django 5.0.6 on 2024-05-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himwaApp', '0003_login2_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='login2',
            name='paid',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='login2',
            name='bill',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
